### ISSUE TITLE
Responsiveness on "About Me" Section

### ISSUE THREAD

**Issue by Natural-H** [Brian00111/Brian00111.github.io#2]
On large displays, the image is over the text, which covers a part of it.
And on small displays, it seems your image isn't in the right place.

Tested:
1920x1080p
360x640p

I know, it's a small detail, but if it's your portfolio, it's better to leave it as polished as possible.`

Large:

![image](https://user-images.githubusercontent.com/76983239/120646804-7fbcde80-c43f-11eb-9b41-d84684b7fe94.png)

Small:

![image](https://user-images.githubusercontent.com/76983239/120647404-328d3c80-c440-11eb-8158-9d6a472a06e6.png)

**Comment by Natural-H** [comment]
~~I tried some things on the issue, sorry about that~~

**Comment by Brian00111** [comment]
Thx Bro!
